[mongodb]
mongodb.cloudskills.fun

[mysql]
mysql.cloudskills.fun

[redis]
redis.cloudskills.fun

[rabbitmq]
rabbitmq.cloudskills.fun

[catalogue]
catalogue.cloudskills.fun

[user]
user.cloudskills.fun

[cart]
cart.cloudskills.fun

[frontend]
frontend.cloudskills.fun

[local]
localhost

[all:vars]
ansible_user=ec2-user 
ansible_password=DevOps321

; [local:vars]
; nme=Vikas
; designation=devops engineer